name: 2.1.$(devops_buildNumber)

pr:
  branches:
    include:
    - master
    - dev
    - v3.x

trigger:
  branches:
    include:
    - dev
    - master

pool:
  vmImage: 'vs2017-win2016'

variables:
  devops_buildNumber: $[counter(format(''), 1500)]

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
- task: OneLocBuild@2
  inputs:
    locProj: 'Build\Localize\LocProject.json'
    outDir: '$(Build.Repository.LocalPath)'
    packageSourceAuth: 'patAuth'
    patVariable: '$(ONELOCBUILD)'
- task: PowerShell@2
  env:
    localPath: $(Build.Repository.LocalPath)
  inputs:
    filePath: '.\Build\LocbuildPostProcessing.ps1'
  displayName: 'Copy localized files'
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: '.\Build'
- task: Gulp@1
  inputs:
    buildNumber: $(devops_buildNumber)
    gulpFile: '.\Build\gulpfile.js'
    targets: 'build-all'
    enableCodeCoverage: false
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.Repository.LocalPath)\bin\VS'
    Contents: '*.nupkg'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: true
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.Repository.LocalPath)\bin'
    Contents: '*.zip'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: false
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
